--liquibase formatted sql
--changeset izec:1

create table usr
(
    id              int8 generated by default as identity,
    activation_code varchar(255),
    active          boolean not null,
    email           varchar(255),
    firstname       varchar(255),
    lastname        varchar(255),
    phone_number    varchar(255),
    primary key (id)
);
create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);
create table account
(
    id      int8 generated by default as identity,
    balance numeric(19, 2),
    number  bigint,
    user_id int8,
    primary key (id)
);
create table card
(
    id         int8 generated by default as identity,
    balance    numeric(19, 2),
    number     bigint,
    password   varchar(255),
    account_id int8,
    primary key (id)
);
create table card_currencies
(
    card_id    int8 not null,
    currencies varchar(255)
);
alter table if exists usr
    add constraint UK_cuhxcprxsgblhlfl0d09o0bhw unique (phone_number);
alter table if exists user_role
    add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references usr;
alter table if exists account
    add constraint FK28fcmglr2tde6x16oxmjor8ux foreign key (user_id) references usr;
alter table if exists account
    add constraint UK_dbfiubqahb32ns85k023gr6nn unique (number);
alter table if exists card
    add constraint UK_492xmgvvn7qbnwhcvpr3yor6h unique (number);
alter table if exists card
    add constraint FK8v67eys6tqflsm6hrdgru2phu foreign key (account_id) references account;
alter table if exists card_currencies
    add constraint FKr5vcjfsjt1raor77illy0w1tn foreign key (card_id) references card;

--changeset izec:2
insert into usr (activation_code, active, email, firstname, lastname, phone_number)
VALUES ('3456',
        'true',
        'some@mail.ru',
        'Alex',
        'Echo',
        '89255431017'),
       ('4856',
        'true',
        'exclusive@mail.ru',
        'Inna',
        'Guk',
        '89201899878');
insert into account (balance, number, user_id)
values (2843,
        '498365656565',
        1),
       (6787,
        '354545454445',
        2);
insert into card (balance, number, password, account_id)
VALUES (2843,
        99956789,
        1234,
        1),
       (6787,
        42766300,
        4343,
        2);
insert into user_role (user_id, roles)
VALUES (1,
        'USER'),
       (2,
        'USER');
insert into card_currencies (card_id, currencies)
VALUES (1,
        'RUB'),
       (2,
        'USD');
